# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Folder-POP3
version:      1.01
version_from: lib/Email/Folder/POP3.pm
installdirs:  site
requires:
    Email::Folder:                 0.84
    Email::FolderType::Net:        1.02
    Net::POP3:                     2.28
    Test::More:                    0.47
    URI:                           1.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
